platform :ios, '12.0'

use_frameworks!
target 'JXPagingViewExample' do
pod 'JXPagingView/Paging', :path => '../../../JXPagingView'
pod 'MJRefresh', '3.4.0'
pod 'JXSegmentedView'
end


post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
        end
    end
end
